from turtle import Turtle , Screen
my_turtle = Turtle()
screen = Screen()

print(my_turtle,screen.canvheight)

my_turtle.shape("turtle")
my_turtle.color("coral")
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.forward(50)
my_turtle.right(60)
my_turtle.color("black")
my_turtle.forward(50)
my_turtle.left(60)
my_turtle.forward(50)
my_turtle.left(60)
my_turtle.forward(50)
my_turtle.left(60)
my_turtle.forward(50)
my_turtle.left(60)
my_turtle.forward(50)
my_turtle.left(60)
my_turtle.forward(50)
my_turtle.left(60)
screen.exitonclick()